"""add interpretation field to appointment model

Revision ID: 5986a81da90d
Revises: f04b717e32ab
Create Date: 2024-11-19 13:40:59.671210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5986a81da90d'
down_revision = 'f04b717e32ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interpretation', sa.Text(), nullable=True))

    with op.batch_alter_table('measure_range', schema=None) as batch_op:
        batch_op.alter_column('upper',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('lower',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measure_range', schema=None) as batch_op:
        batch_op.alter_column('lower',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('upper',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('interpretation')

    # ### end Alembic commands ###
