"""Initial migration.

Revision ID: 672dce9b03bd
Revises: 
Create Date: 2024-10-27 16:21:07.667567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '672dce9b03bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column('doctor_notes',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column('doctor_notes',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
