"""Initial migration.

Revision ID: 9abbbd2c21e0
Revises: 1f18d0659f63
Create Date: 2024-10-29 18:01:40.972605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9abbbd2c21e0'
down_revision = '1f18d0659f63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('creation_date', sa.DateTime(), nullable=False))
        batch_op.drop_column('date')
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=80), nullable=False))
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=False))
        batch_op.drop_column('creation_date')
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###
