"""Initial migration.

Revision ID: f04b717e32ab
Revises: 9abbbd2c21e0
Create Date: 2024-11-17 15:06:14.816000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f04b717e32ab'
down_revision = '9abbbd2c21e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measure_range', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_gender_per_measure_id', ['gender', 'measure_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measure_range', schema=None) as batch_op:
        batch_op.drop_constraint('unique_gender_per_measure_id', type_='unique')

    # ### end Alembic commands ###
